remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
title: Home Assistant PC Switch
description: Control your PC from Home Assistant using EPSHome or Tasmota.
show_downloads: false
