title: Home Assistant PC Switch
description: Control your PC from Home Assistant using EPSHome or Tasmota.
logo: /assets/img/logo.png

google_analytics:
# theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: false
