title: HA PC Switch
description: Automate power on your PC using ESPHome or Tasmota, and integrated into Home Assistant.
logo: /assets/img/logo.png

google_analytics:
# theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: false
